
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.237
    token: 643674636c437449386e6a647379534c


